version: "3.5"

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "1337:3000"
    volumes:
      - .:/api
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://cache
      - MAX_UPLOAD_SIZE=3145728
    networks:
      - backend

  db:
    image: postgres
    networks:
      - backend

  redis:
    image: redis
    container_name: cache
    networks:
      - backend

volumes:
  node_modules:
  build_folder:

networks:
  frontend:
    driver: bridge
