# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9236be9f1b6e70446b5835a1b475e4e8e89ddd9ecdace51bdb47fd1e03ede7156a3d7231dfb0a6b41d71cc26a4a57dd774ee5ce7865326199fed5f9f782b5143

test:
  secret_key_base: fca481505ec4ed466224918ccac0c3af697ad73af0539607e8444270005a9e6a2e61118b48025bdc271d88d648b08589850d7325f4efb2628e2d222b00302830

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
